# Generated by Django 5.2.5 on 2026-10-01 06:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0018_assign_asm_group_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolemonthlyquota',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('200000.00'), max_digits=12),
        ),
    ]
