# Generated by Django 5.2.5 on 2026-10-08 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0026_increase_company_name_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerhistory',
            name='action',
            field=models.CharField(choices=[('created', 'Customer Created'), ('updated', 'Customer Updated'), ('vip_enabled', 'Became VIP Customer'), ('vip_disabled', 'VIP Status Removed'), ('activated', 'Customer Activated'), ('deactivated', 'Customer Deactivated'), ('salesperson_assigned', 'Salesperson Assigned'), ('salesperson_changed', 'Salesperson Changed'), ('salesperson_removed', 'Salesperson Removed'), ('restored', 'Restored from Backup'), ('imported', 'Imported from CSV'), ('field_updated', 'Field Updated'), ('deal_won', 'Deal Marked Won'), ('deal_lost', 'Deal Marked Lost'), ('funnel_entry_removed', 'Funnel Entry Removed'), ('funnel_entry_restored', 'Funnel Entry Restored')], help_text='Type of action performed', max_length=25),
        ),
    ]
