# Generated by Django 5.2.5 on 2026-09-19 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_proposals', '0038_proposal_hide_part_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalapprovalstep',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
