# Generated by Django 5.2.5 on 2026-10-03 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_proposals', '0039_alter_proposalapprovalstep_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='is_test',
            field=models.BooleanField(default=False, help_text='Marks a test/scratch proposal. Its funnel entry becomes deletable.'),
        ),
    ]
