# Generated by Django 5.2.5 on 2026-10-03 11:59

import django.db.models.deletion
import file_sharing.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_sharing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyFileShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Descriptive title for the file', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional description of the file contents')),
                ('file', models.FileField(upload_to=file_sharing.models.get_company_file_upload_path, validators=[file_sharing.models.validate_company_file_size, file_sharing.models.validate_company_file_extension])),
                ('category', models.CharField(choices=[('proposals', 'Proposal Templates'), ('contracts', 'Contracts'), ('presentations', 'Presentations'), ('forms', 'Forms & Documents'), ('resources', 'Resources & Guidelines'), ('training', 'Training Materials'), ('other', 'Other Documents')], default='other', max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this file is available for download')),
                ('download_count', models.PositiveIntegerField(default=0, help_text='Number of times this file has been downloaded')),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_company_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company File Share',
                'verbose_name_plural': 'Company File Shares',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanyFileAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('download', 'Downloaded'), ('view', 'Viewed'), ('upload', 'Uploaded'), ('delete', 'Deleted')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_file_access_logs', to=settings.AUTH_USER_MODEL)),
                ('file_share', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='file_sharing.companyfileshare')),
            ],
            options={
                'verbose_name': 'Company File Access Log',
                'verbose_name_plural': 'Company File Access Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
