# Generated by Django 5.2.5 on 2026-10-03 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_funnel', '0008_alter_salesfunnel_salesperson'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesfunnel',
            name='is_test',
            field=models.BooleanField(default=False, help_text='Marks a throwaway test/scratch entry. Only test entries may be deleted.'),
        ),
    ]
