# Generated by Django 5.2.5 on 2026-10-08 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_funnel', '0009_salesfunnel_is_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesfunnel',
            name='lost_reason',
            field=models.TextField(blank=True, help_text='Why this deal was lost. Required when marking a deal LOST so the team can learn from it; shown in deal history.'),
        ),
    ]
