# Generated by Django 5.2.5 on 2026-10-08 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_funnel', '0010_salesfunnel_lost_reason'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salesfunnel',
            name='removed_at',
            field=models.DateTimeField(blank=True, help_text='When this entry was removed from the active pipeline.', null=True),
        ),
        migrations.AddField(
            model_name='salesfunnel',
            name='removed_by',
            field=models.ForeignKey(blank=True, help_text='The user who removed this entry from the pipeline.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='removed_funnel_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesfunnel',
            name='removed_reason',
            field=models.TextField(blank=True, help_text='Why this entry was removed from the pipeline. Required when removing a real entry; kept for supervisor review.'),
        ),
    ]
